### ISSUE TITLE
Why delete history?

### ISSUE THREAD

**Issue by Rouji** [Gurkengewuerz/php_filehost#1]
Hi! I've only just discovered this repo.  
Why did you completely delete my commit history?  
My project didn't have a license for a long time ([it does now](https://github.com/Rouji/single_php_filehost/blob/master/LICENSE)), which made forking a bit questionable in any case, but I don't mind that aspect that much.  
What I find weird is that you've even linked my repo in the readme... So why rewrite history so I'm not in it? Big chunks of code are clearly still one-to-one verbatim my code.

**Comment by Gurkengewuerz** [comment]
Hey @Rouji thanks for your request. TBH this project is almost 4 years ago and i don't really know why i never forked your project neither keep the history.
I now merged your code history from 2017 into this repo and let you of course mentioned by name in the readme as well as on the page of the PHP script.
I hope you agree with this so far. If not please contact me.

**Comment by Rouji** [comment]
Yep, that seems to have fixed the history thing. Thanks!  
I think license-wise it might still be questionable(?), but I'm not gonna have you jump through any more hoops or anything. I'm not *that* bothered. If this repo completely blows up or something, we can still have that discussion then. lol
